CREATE EXTERNAL TABLE IF NOT EXISTS fcst_clean_${env}.dsy_weather (
    tti_type_tiers          SMALLINT,
    tir_num_tiers           SMALLINT,
    tir_sous_num_tiers      SMALLINT,
    countrycode             STRING,
    latitude                DOUBLE,
    longitude               DOUBLE,
    day_id_day              DATE,
    summary                 STRING,
    icon                    STRING,
    moonphase               DOUBLE,
    preciintensity          DOUBLE,
    precipintensitymax      DOUBLE,
    precipprobability       DOUBLE,
    preciptype              STRING,
    temperaturehigh         DOUBLE,
    temperaturelow          DOUBLE,
    apparenttemperaturehigh DOUBLE,
    apparenttemperaturelow  DOUBLE,
    dewpoint                DOUBLE,
    humidity                DOUBLE,
    pressure                DOUBLE,
    windspeed               DOUBLE,
    windgust                DOUBLE,
    windbearing             DOUBLE,
    cloudcover              DOUBLE,
    uvindex                 DOUBLE,
    visibility              DOUBLE,
    ozone                   DOUBLE,
    temperaturemin          DOUBLE,
    temperaturemax          DOUBLE,
    apparenttemperaturemin  DOUBLE,
    apparenttemperaturemax  DOUBLE,
    rs_technical_date       TIMESTAMP,
    rs_technical_flow       STRING
)
STORED AS PARQUET
LOCATION 's3://fcst-clean-${env}/datalake/dsy_weather/'
;