CREATE EXTERNAL TABLE IF NOT EXISTS fcst_clean_${env}.f_delivery_detail (
    the_transaction_id                   STRING,
    dyh_num_line_delivery                INT,
    tdt_num_line                         INT,
    dyh_date_canceled                    TIMESTAMP,
    tdt_date_to_ordered                  TIMESTAMP,
    dyd_date_to_invoiced                 TIMESTAMP,
    the_date_transaction                 TIMESTAMP,
    the_date_authorized                  TIMESTAMP,
    the_transaction_status               STRING,
    sku_idr_sku                          BIGINT,
    tdt_item_id                          STRING,
    mhy_idr_merchandise_hie              SMALLINT,
    but_idr_business_unit                BIGINT,
    but_idr_business_unit_fiscal         BIGINT,
    but_idr_business_unit_economical     BIGINT,
    but_idr_business_unit_sender         BIGINT,
    but_idr_business_unit_clic_n_collect BIGINT,
    but_idr_business_unit_receiver       BIGINT,
    but_idr_business_unit_stock_origin   BIGINT,
    cnt_idr_country                      BIGINT,
    cur_idr_currency                     BIGINT,
    rrn_idr_return_reason                SMALLINT,
    rty_idr_return_type                  SMALLINT,
    tpc_idr_touchpoint_channel_type      SMALLINT,
    rdt_idr_reallocated_digital_type     SMALLINT,
    frm_idr_freight_method               BIGINT,
    sht_idr_shipping_type                SMALLINT,
    tdt_type_detail                      STRING,
    cct_idr_customer_channel_type        SMALLINT,
    ctt_idr_customer_type                SMALLINT,
    dyh_zip_code                         STRING,
    ctm_customer_id                      STRING,
    ctm_zip_code                         STRING,
    tdt_item_type                        STRING,
    tcn_idr_transaction_channel_type     SMALLINT,
    the_to_type                          STRING,
    f_tdt_pri_regular_sales_unit         DECIMAL(22,6),
    f_tdt_qty_item                       INT,
    f_tdt_pri_unit_cost_price            DECIMAL(22,6),
    f_tdt_margin_estimate                DECIMAL(22,6),
    f_dyh_amt_shipping_fee               DECIMAL(22,6),
    f_to_tax_in                          DECIMAL(22,6),
    f_to_tax_ex                          DECIMAL(22,6),
    f_amt_discount                       DECIMAL(22,6),
    f_qty_item                           INT,
    f_pri_unit_cost_price                DECIMAL(22,6),
    f_amt_tax                            DECIMAL(22,6),
    f_margin_real                        DECIMAL(22,6),
    data_origin                          STRING
)
PARTITIONED BY (month STRING)
STORED AS PARQUET
LOCATION 's3://fcst-clean-${env}/datalake/f_delivery_detail/'
;