CREATE EXTERNAL TABLE IF NOT EXISTS fcst_clean_${env}.f_transaction_detail (
    the_transaction_id                 string,
    tdt_num_line                       int,
    tdt_date_to_ordered                timestamp,
    the_date_transaction               timestamp,
    the_date_authorized                timestamp,
    tdt_date_updated                   string,
    sku_idr_sku                        BIGINT,
    tdt_item_id                        string,
    mhy_idr_merchandise_hie            SMALLINT,
    but_idr_business_unit              BIGINT,
    cnt_idr_country                    BIGINT,
    tpc_idr_touchpoint_channel_type    SMALLINT,
    wks_serial_number                  string,
    cur_idr_currency                   BIGINT,
    rrn_idr_return_reason              SMALLINT,
    rty_idr_return_type                SMALLINT,
    cct_idr_customer_channel_type      SMALLINT,
    ctt_idr_customer_type              SMALLINT,
    ctm_customer_id                    string,
    ctm_zip_code                       string,
    tcn_idr_transaction_channel_type   SMALLINT,
    the_to_type                        string,
    the_transaction_status             string,
    tdt_item_type                      string,
    tdt_type_detail                    string,
    tdt_entry_method                   string,
    f_pri_manufacturer_suggested_price decimal(22,6),
    f_pri_regular_sales_unit           decimal(22,6),
    f_to_tax_in_initial                decimal(22,6),
    f_to_tax_ex_initial                decimal(22,6),
    f_qty_item_initial                 int,
    f_amt_discount_initial             decimal(22,6),
    f_amt_tax_initial                  decimal(22,6),
    f_to_tax_in                        decimal(22,6),
    f_to_tax_ex                        decimal(22,6),
    f_amt_discount                     decimal(22,6),
    f_qty_item                         int,
    f_pri_unit_cost_price              decimal(22,6),
    f_margin_estimate                  decimal(22,6),
    f_amt_tax                          decimal(22,6),
    data_origin                        string
)
PARTITIONED BY (month string)
STORED AS PARQUET
LOCATION 's3://fcst-clean-${env}/datalake/f_transaction_detail/'
;