CREATE EXTERNAL TABLE IF NOT EXISTS fcst_clean_${env}.mst_d_tiers (
    id                           INT,
    tti_type_tiers               SMALLINT,
    tir_num_tiers                INT,
    tir_sous_num_tiers           INT,
    storename                    STRING,
    countrycode                  STRING,
    selectedlanguages            STRING,
    directorsignature            STRING,
    openingstore                 STRING,
    workshop                     STRING,
    storereviews                 STRING,
    addressline1                 STRING,
    addressline2                 STRING,
    postalcode                   STRING,
    city                         STRING,
    region                       STRING,
    phone                        STRING,
    contacturl                   STRING,
    facebookurl                  STRING,
    twitteraccount               STRING,
    googleplusaccount            STRING,
    latitude                     STRING,
    longitude                    STRING,
    welcomepicture               STRING,
    url_website                  STRING,
    third_opening_time_monday    STRING,
    third_opening_time_tuesday   STRING,
    third_opening_time_wednesday STRING,
    third_opening_time_thursday  STRING,
    third_opening_time_friday    STRING,
    third_opening_time_saturday  STRING,
    third_opening_time_sunday    STRING,
    third_closing_time_monday    STRING,
    third_closing_time_tuesday   STRING,
    third_closing_time_wednesday STRING,
    third_closing_time_thursday  STRING,
    third_closing_time_friday    STRING,
    third_closing_time_saturday  STRING,
    third_closing_time_sunday    STRING,
    rs_technical_date            TIMESTAMP,
    rs_technical_flow            STRING
)
STORED AS PARQUET
LOCATION 's3://fcst-clean-${env}/datalake/mst_d_tiers/'
;